#!/bin/bash

# Upload script for HuggingFace
echo "========================================"
echo "HuggingFace Model Upload Instructions"
echo "========================================"
echo ""
echo "To upload your trained model to HuggingFace, follow these steps:"
echo ""
echo "1. Install HuggingFace CLI (if not already installed):"
echo "   pip install huggingface-hub"
echo ""
echo "2. Login to HuggingFace:"
echo "   huggingface-cli login"
echo ""
echo "3. Create the model repository:"
echo "   huggingface-cli repo create poster-metadata-crf --type model"
echo ""
echo "4. Clone the repository:"
echo "   git clone https://huggingface.co/jimnoneill/poster-metadata-crf"
echo ""
echo "5. Copy model files:"
echo "   cp pytorch_model.bin config.json README.md ../poster-metadata-crf/"
echo "   cp -r tokenizer_config.json special_tokens_map.json vocab.txt ../poster-metadata-crf/"
echo ""
echo "6. Push to HuggingFace:"
echo "   cd ../poster-metadata-crf"
echo "   git add ."
echo "   git commit -m 'Add trained Transformer+CRF model for poster extraction'"
echo "   git push"
echo ""
echo "========================================"
echo ""
echo "Model files ready for upload:"
ls -la *.pt *.bin *.json *.txt *.md 2>/dev/null | grep -E "\.(pt|bin|json|txt|md)$"


